<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DotTiingo</Title>
    <Authors>Grovre</Authors>
    <Description>Easy library for access to Tiingo's API</Description>
    <PackageProjectUrl>https://github.com/Grovre/DotTiingo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Grovre/DotTiingo</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>tiingo;finance;stock;stocks;crypto;forex;iex;market-data;rest;websocket</PackageTags>
    <PackageOutputPath>$(OutputPath)</PackageOutputPath>
    <Copyright>© 2026 Grovre</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Version>1.3.0</Version>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Testing" />
  </ItemGroup>

</Project>
